### PR TITLE
Added linked dates support

### PR DESCRIPTION
**Pull request by bgk0018**
See https://github.com/alangrainger/obsidian-frontmatter-modified-date/issues/22

### CODE REVIEW

**Comment by alangrainger** [comment]
Thank you for the PR, but there is no need for it as you can just use the standard [MomentJS date format](https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/) to add the extra non-date characters ([[ and ]]), and your dates will show as links.

Set your date format in the plugin settings to be:

```
[[[]YYYY-MM-DD[]]]
```

**Comment by tkern** [comment]
I am probably too daft but how do you combine this with other moment.js tokens?

i can get it to output:
`- Sunday, "[[2024-10-06]]" 1:01:40 pm` by using `dddd, "[[[]YYYY-MM-DD[]]][""] h:mm:ss a` but obsidian does not pick up the link between the two files

**Comment by alangrainger** [comment]
@tkern you haven't done anything wrong - Obsidian itself will not parse that. If you want to have a property be a link, it cannot have any other non-link text.

**Comment by tkern** [comment]
> @tkern you haven't done anything wrong - Obsidian itself will not parse that. If you want to have a property be a link, it cannot have any other non-link text.

Did not know that. I have done a workout which seems to work (picks up backlink and is clickable). Also gets updated correctly by this plugin!

`[[[]YYYY-MM-DD|dddd, MMMM Do YYYY, hh:mm a[]]]`

full credit goes to @Tainmere for suggesting the link text workaround.

**Pull request closed without merging**
